### PR TITLE
#13-feat/add home page

### PR DESCRIPTION
**Pull request by AdrianFerrari**

### CODE REVIEW

**Comment by tomasbirbe** [comment]
Rename Store folder to "Stores" in order to match with the route

**Comment by tomasbirbe** [comment]
Types and Sizes are executing when one of them are updated.

**Comment by AdrianFerrari** [comment]
> Types and Sizes are executing when one of them are updated.

I split the Categories component into two, Size and Types
Both use their own function to determine their respective categories.
Below I tested them under heavy load.

Test: 10000 product objects with 50 categories y 50 sizes each.

First render
Size => 254.7ms 1.2% of total page load time
Types => 241.7ms 1.2%
Second render: changing store and coming back
Size => 482.2ms 2.6%
Types => 472.8ms 2.5%

Second test
First render
Size => 259.5ms 1.6%
Types => 230.2ms 1.4%
Second render: changing store and coming back
Size => 532.8ms 2.6%
Types => 512.9ms 2.5%

with useMemo
First render
Sizes => 253.2ms 1.2%
Types => 238.7ms 1.1%
Second render: changing store and coming back
Sizes => 241.1ms
Types => 244.2ms

with useState
First render
Sizes => 253.5ms
Types => 262.7ms
Second render: changing store and coming back
Sizes => 246.3ms
Types => 245.5ms

Solution:
Switched to using useState.

**Comment by tomasbirbe** [comment]
Delightful solution.

**Pull request merged**
